"""
editor_agent.py — YAHWAYLOVE EDITOR Agent
==========================================
Theology + tone QA pass on posts generated by CONTENT agent.
Reviews each post against the pastor's voice profile and returns
a verdict (PASS / REVISE) with specific notes.

Usage:
    python editor_agent.py --sprint SPRINT-2026-04-19-JW
    python editor_agent.py --sprint SPRINT-2026-04-19-JW --auto-revise
    python editor_agent.py --file posts/SPRINT-2026-04-19-JW/raw_posts.md

Outputs:
    posts/[sprint_id]/reviewed_posts.md   — approved posts, delivery-ready
    posts/[sprint_id]/editor_report.md    — full QA report with notes per post

Requirements:
    pip install anthropic python-dotenv
    ANTHROPIC_API_KEY in agents/.env
"""

import anthropic
import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# ── System prompt ─────────────────────────────────────────────────────────────

EDITOR_SYSTEM = """
You are EDITOR, the Quality Assurance Agent for YAHWAYLOVE LLC.

You review faith content generated by the CONTENT agent before it reaches real pastors
and their congregations. Your review is the last line of defense.

You check for:

THEOLOGY
- Scripture references: are they real, correctly attributed, and in the right translation?
- Doctrinal accuracy: does the content align with the pastor's stated theological tradition?
- No prosperity gospel, word-of-faith excess, or theological overreach
- No statements that would embarrass the pastor doctrinally

VOICE FIDELITY
- Does this sound like the pastor or like a generic AI post?
- Are their tone dial scores respected?
- Does it avoid their Avoid List phrases?
- Does the closing move match their stated pattern?

QUALITY
- Is the hook compelling enough to stop a scroll?
- Is the length appropriate for the post type?
- No clichés or Christianese that the pastor wouldn't use
- Would this post generate real engagement from their congregation?

VERDICT per post:
- PASS: Ready to deliver. Minor polish only.
- REVISE: Specific problems noted. CONTENT agent must rewrite.

Be direct. Be specific. These posts represent a real pastor's public voice.
"""

REVIEW_PROMPT = """
Pastor Voice Profile:
{profile}

---

Posts to review:
{posts}

---

Review each post. For each one output:

### Post [N] — [Type] — [PASS or REVISE]

**Theology check:** [Pass / Issue: describe specifically]
**Voice fidelity:** [Pass / Issue: describe specifically]
**Quality:** [Pass / Issue: describe specifically]
**Notes:** [Any specific notes — if REVISE, be exact about what to fix]
**Revised text (if REVISE):** [Write the corrected post inline — do not leave blanks]

After all posts, output:

---
## Delivery Summary
- Posts approved: [N]/10
- Posts revised: [N]/10
- Overall quality: [Excellent / Good / Needs work]
- Ready for delivery: [Yes / No — reason if No]
"""

EXTRACT_APPROVED_PROMPT = """
You are compiling the final approved posts for delivery to a pastor.

Here is the full EDITOR review report:
{report}

Extract ONLY the final approved text for each post. For posts marked PASS, use
the original text. For posts marked REVISE, use the "Revised text" provided by
the EDITOR.

Output in this exact format — clean, ready to copy/paste or email:

---

## Post 1 — [Type]
[post text]

---

## Post 2 — [Type]
[post text]

[...continue for all 10 posts...]

---

No review notes. No verdict labels. Just the clean post text for each.
"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def find_sprint_dir(sprint_id: str) -> Path:
    """Locate the sprint output directory."""
    sprint_dir = Path(f"posts/{sprint_id}")
    if not sprint_dir.exists():
        print(f"\n  ✗  Sprint directory not found: {sprint_dir}")
        print(f"     Run content_agent.py --profile <profile> first.\n")
        sys.exit(1)
    return sprint_dir


def load_raw_posts(sprint_dir: Path) -> str:
    """Load raw_posts.md or free_sample.md from sprint dir."""
    for fname in ["raw_posts.md", "free_sample.md"]:
        fpath = sprint_dir / fname
        if fpath.exists():
            with open(fpath) as f:
                return f.read()
    print(f"\n  ✗  No raw posts found in {sprint_dir}\n")
    sys.exit(1)


def load_profile_from_summary(sprint_dir: Path) -> str:
    """Extract the profile snippet stored in intake_summary.md."""
    summary_path = sprint_dir / "intake_summary.md"
    if not summary_path.exists():
        return "[Voice profile not available — review manually]"
    with open(summary_path) as f:
        content = f.read()
    # Extract the profile block from the summary
    match = re.search(r"## Profile Used\n```\n(.+?)```", content, re.DOTALL)
    if match:
        return match.group(1).strip()
    return content


def run_editor_review(profile: str, posts: str) -> str:
    """Run EDITOR review via Claude."""
    print("  ⟳  Running EDITOR review...")

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=8096,
        system=EDITOR_SYSTEM,
        messages=[{
            "role": "user",
            "content": REVIEW_PROMPT.format(profile=profile, posts=posts)
        }],
    )
    return response.content[0].text


def extract_final_posts(report: str) -> str:
    """Use Claude to extract clean delivery-ready posts from the report."""
    print("  ⟳  Compiling approved posts...")

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=6000,
        messages=[{
            "role": "user",
            "content": EXTRACT_APPROVED_PROMPT.format(report=report)
        }],
    )
    return response.content[0].text


def parse_delivery_summary(report: str) -> dict:
    """Extract pass/revise counts from the editor report."""
    approved_match = re.search(r"Posts approved:\s*(\d+)", report)
    revised_match = re.search(r"Posts revised:\s*(\d+)", report)
    ready_match = re.search(r"Ready for delivery:\s*(Yes|No)", report)

    return {
        "approved": int(approved_match.group(1)) if approved_match else "?",
        "revised": int(revised_match.group(1)) if revised_match else "?",
        "ready": ready_match.group(1) if ready_match else "Unknown",
    }


def save_outputs(
    sprint_dir: Path,
    report: str,
    final_posts: str,
    sprint_id: str,
) -> None:
    """Save editor report and reviewed posts."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Save editor report
    report_file = sprint_dir / "editor_report.md"
    with open(report_file, "w") as f:
        f.write(f"# EDITOR QA Report — {sprint_id}\n**Reviewed:** {timestamp}\n\n")
        f.write(report)

    # Save delivery-ready posts
    reviewed_file = sprint_dir / "reviewed_posts.md"
    with open(reviewed_file, "w") as f:
        f.write(f"# Delivery-Ready Posts — {sprint_id}\n")
        f.write(f"**Reviewed:** {timestamp}\n")
        f.write(f"**Status:** EDITOR APPROVED — Ready to deliver to pastor\n\n")
        f.write(final_posts)

    print(f"\n  ✓  Editor report → {report_file}")
    print(f"  ✓  Delivery posts → {reviewed_file}")


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="YAHWAYLOVE EDITOR Agent")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--sprint", type=str, help="Sprint ID (e.g. SPRINT-2026-04-19-JW)")
    group.add_argument("--file", type=str, help="Direct path to raw_posts.md")
    parser.add_argument("--profile", type=str, help="Path to pastor.md (optional override)")
    args = parser.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("\n  ✗  ANTHROPIC_API_KEY not found in .env\n")
        sys.exit(1)

    print("\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("  YAHWAYLOVE — EDITOR Agent")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

    # Locate files
    if args.sprint:
        sprint_id = args.sprint
        sprint_dir = find_sprint_dir(sprint_id)
    else:
        posts_file = Path(args.file)
        sprint_dir = posts_file.parent
        sprint_id = sprint_dir.name

    # Load content
    raw_posts = load_raw_posts(sprint_dir)

    if args.profile:
        with open(args.profile) as f:
            profile = f.read()
    else:
        profile = load_profile_from_summary(sprint_dir)

    print(f"  Sprint ID: {sprint_id}")
    print(f"  Posts dir: {sprint_dir}\n")

    # Run review
    report = run_editor_review(profile=profile, posts=raw_posts)

    # Extract clean posts
    final_posts = extract_final_posts(report)

    # Parse summary
    summary = parse_delivery_summary(report)

    # Save
    save_outputs(sprint_dir, report, final_posts, sprint_id)

    # Print summary
    print(f"\n  ━━━ EDITOR SUMMARY ━━━")
    print(f"  Posts approved: {summary['approved']}/10")
    print(f"  Posts revised:  {summary['revised']}/10")
    print(f"  Ready to deliver: {summary['ready']}")
    print(f"\n  ✓  Next step: send posts/{sprint_id}/reviewed_posts.md to pastor")
    print(f"     Or run: python sprint_runner.py --sprint {sprint_id} --deliver\n")


if __name__ == "__main__":
    main()
